refactor(mdag): Remove Selenium
freelawproject/juriscraper pull request #460
Opened 2021-12-29 02:43 UTC by flooie

Remove selenium for MDAG

Update tests for our new method - and delete
the one that was empty and not working.

We have a surprisingly high number of broken/empty tests

2021-12-29 23:16 UTC, mlissner requested changes
Well, this got easier! 

I assume you checked that CI works on the JSON fixture you provided?

2021-12-29 23:16 UTC, mlissner commented on juriscraper/opinions/united_states/state/mdag.py
> +                    "date": row["Created_x0020_Date"][3:13],
Can you give an example of what `3:13` is handling, please?

2021-12-29 23:29 UTC, flooie commented
Cl?

2021-12-29 23:42 UTC, mlissner commented
> Cl?

Continuous Integration (Github Actions).

2021-12-30 06:36 UTC, mlissner commented on juriscraper/opinions/united_states/state/mdag.py
> +                    "date": row["Created_x0020_Date"][3:13],
OK, so seeing that example (which I'd expect above the `"date"` line), not above the `append()`, I wonder if we should grab the date by regex or by splitting on the `#`, etc. I just worry that too much can change in that random string at the beginning.

2021-12-30 17:49 UTC, flooie commented
Back to you.

2021-12-30 20:37 UTC, merged