Do and additional GET request when a PACER login page is returned.
freelawproject/juriscraper pull request #618
Opened 2023-01-10 22:09 UTC by albertisfu

As described in [#2160 ](https://github.com/freelawproject/courtlistener/issues/2160)sometimes a PACER login page is shown after a GET request, even though cookies are still valid. Usually doing additional requests solve the problem and the requested content is returned.

So in this PR, I added some code to do 1 additional GET request after `check_if_logged_in_page` returns `False`. So this would save retries and hopefully fewer PACERLoginExceptions would be raised into Sentry.

This logic only applies to PACER GET requests, since we don't have problems with POST requests according to sentry.

I did some tests in CL using this approach and seems to work, without this logic on a failing `fetch_attachment_page` task, it took on average 4-5 retries or failed to get the attachment page.  
While using this logic it took on average 1-3 retries to get the attachment page.

Let me know what you think.

2023-01-24 00:30 UTC, mlissner requested changes
Hm, I'm fine with the idea of logging in again if we hit the page looking for a client code, but this solution feels pretty hard to understand. 

There's a new class attribute for `check_if_logged_in_count` which gets set to 0 and 1 here and there, and there's a spot that checks for it before doing stuff. All pretty magical stuff. 

A couple different approaches that might work better:

 - Check if it's the claims page when something fails and do something.
 - Use an attribute that can be set to True/False instead of a confusing count that has magical meaning.
 - Centralize the logic somewhere so we don't have to put tests for `== 0` or `==1` in various places. 

Mind taking another look at this for something more elegant?

2023-01-24 15:38 UTC, albertisfu commented
Got it, sure I'll check this in order to get something better.
Thanks for the suggestions!

2023-01-25 18:16 UTC, albertisfu commented
I've applied the suggestions, use a `boolean` instead of an `integer`, and centralized the logic in a new method.

About your other comment, since this is the page that is raised when this error happens.
![Screenshot 2023-01-25 at 12 03 42](https://user-images.githubusercontent.com/486004/214645806-56249a22-5b75-4e78-91d1-e2dad3237ec7.png)

You mentioned that a client code is just used for billing, so doing some manual testing when this page is raised I added a random string as client code and a similar behavior happened, sometimes on submit the resource was properly shown, and sometimes the same page is shown again, so seems that adding a client code to the request doesn't help more than just submitting the request.

Let me know what you think.
Thanks.

2023-01-25 20:46 UTC, mlissner approved these changes

2023-01-25 20:46 UTC, merged

2023-01-25 20:47 UTC, mlissner commented
This is better for sure. Thanks.