Fix major issues
freelawproject/juriscraper pull request #760
Opened 2023-11-05 13:35 UTC by flooie

cc @mlissner 
Fixes or additions with tests for 46ish scrapers

Alaska
Conn.
Conn App
Fla Dist Ct 1-6
Ga Ct App
Haw
Haw App
Indiana
Ind Ct App
Ind Tax Ct
Kansas
Minn
Minn Ct App (p)
Minn Ct App (u)
Missouri
Mo Ct App Eastern
Mo Ct App Southern
Mo Ct App Western
Nevada
New Hampshire
New Jersey
NJ Super Ct App Div (p)
NJ Super Ct App Div (u)
NJ Tax Court
Oklahoma
Tenn
Tenn Crim App
Tenn Ct App (Civil)
Virginia
VA Ct App (p)
VA Ct App (u)
VT
VT Supreme (Crim)
Vt Super Ct Civ
Vt Super Ct Env
Vt Super Ct Fam
Vt Super Ct Prob
Wash
Wash Ct App (p)
Wash Ct App (u)

2023-11-08 23:46 UTC, mlissner commented
Woah, nelly, this is a big one. I think the best person to review this is probably Kevin. @quevon24 can you put this on your backlog at whatever priority Bill thinks is right?

2023-11-13 23:06 UTC, quevon24 requested changes
Everything looks good, just a small bug in the Minnesota Supreme Court Scraper

2023-11-13 23:26 UTC, flooie commented on juriscraper/opinions/united_states/state/minn.py
> +            docket = url.split("/OP")[1].split("-")[0]
yes - I noticed that the other day.  thanks for catching it .

2023-11-13 23:41 UTC, quevon24 approved these changes

2023-11-13 23:41 UTC, merged